---
- name: Base | Check configuration
  assert:
    that:
      - "domains.lan is defined"
      - "resolvers is iterable"
      - "timezone is defined"
      - "lp.name is defined and lp.rev is defined"
    msg: Complete the basic configuration first

- include: system.yml
  tags: [ 'system' ]

- include: cpupower.yml
  when: ansible_metal and ansible_cpufreq
  tags: [ 'cpupower' ]

- include: packages.yml
  tags: [ 'packages' ]

- include: time.yml
  tags: [ 'time' ]

- include: motd.yml
  tags: [ 'motd' ]

- include: rsyslog.yml
  tags: [ 'syslog', 'rsyslog' ]
